name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'PHPStan'
                        run: composer phpstan

                    -
                        name: 'Check Active Classes'
                        run: vendor/bin/class-leak check src tests --ansi

                    -
                        name: 'Unit tests'
                        run: vendor/bin/phpunit

                    -
                        name: "Finalize classes"
                        run: vendor/bin/swiss-knife finalize-classes src tests --dry-run

                    -
                        name: 'Composer dependency Analyser'
                        run: vendor/bin/composer-dependency-analyser

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: __PHP_VERSION__
                    coverage: none

            -   uses: "ramsey/composer-install@v2"

            -   run: ${{ matrix.actions.run }}
